services:

  mongo:
    image: mongo:latest
    restart: on-failure
    volumes:
      - mg-data:/data
    ports:
      - "27017:27017"
    container_name: flexsearch_mongo_db
volumes:
  pg-data:
    driver: local
  ch-data:
    driver: local
  rd-data:
    driver: local
  mg-data:
    driver: local